export const navigationItems = [
  { id: 'projects', label: 'Projects', icon: 'Folder', href: '/projects', enabled: true },
  { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/tasks', enabled: true },
  { id: 'reports', label: 'Reports', icon: 'BarChart2', href: '/reports', enabled: true },
  { id: 'health', label: 'Health', icon: 'Heart', href: '/health', enabled: true },
  { id: 'finance', label: 'Finance', icon: 'DollarSign', href: '/finance', enabled: true },
  { id: 'cron', label: 'Cron Jobs', icon: 'Clock', href: '/cron', enabled: true },
  { id: 'docs', label: 'Docs', icon: 'BookOpen', href: '/docs', enabled: true },
  { id: 'calendar', label: 'Calendar', icon: 'Calendar', href: 'https://calendar.google.com/calendar', enabled: true, external: true },
  { id: 'conversations', label: 'Conversations', icon: 'MessageSquare', href: '/conversations', enabled: true },
  { id: 'content', label: 'Content', icon: 'FileText', href: '/content', enabled: false },
  { id: 'approvals', label: 'Approvals', icon: 'CheckCircle', href: '/approvals', enabled: false },
  { id: 'council', label: 'Council', icon: 'Users', href: '/council', enabled: false },
  { id: 'memory', label: 'Memory', icon: 'Brain', href: '/memory', enabled: false },
  { id: 'people', label: 'People', icon: 'UserCircle', href: '/people', enabled: false },
  { id: 'office', label: 'Office', icon: 'Briefcase', href: '/office', enabled: false },
  { id: 'team', label: 'Team', icon: 'Users2', href: '/team', enabled: false },
];
